"""
src/agents/visualizer.py

Visualization Agent.

Responsibilities (per the capstone handbook, Section 11.3): consume the
EDA report, ML report, and cleaned data to produce the chart images used
in the dashboard and final PDF report.

Design note: like the preceding agents this is fully deterministic — pure
matplotlib/seaborn, no LLM calls. Each chart is generated by a dedicated
private method so it can be unit-tested in isolation. The agent handles
missing/incomplete upstream reports gracefully: if a required piece of data
is absent (e.g. empty feature_importances) the relevant chart is skipped
and logged as a warning rather than crashing.

Genericity (handbook Section 8.2): this agent must work for classification
AND regression, on any dataset. It branches on ml_report["task_type"]:
  * classification (binary/multiclass): confusion-matrix heatmap +
    decision-threshold tradeoff line chart, and a box plot of the top
    feature split by class.
  * regression: actual-vs-predicted scatter (diagonal = perfect
    prediction) + residual plot (predicted vs. actual-minus-predicted,
    zero line), and a scatter of the top feature against the continuous
    target. These read MLReport's "test_predictions" field -- the exact
    held-out (actual, predicted) pairs MLAgent used to compute RMSE/MAE,
    so the charts are guaranteed consistent with the reported metrics
    rather than reconstructed independently.

Binary classification chart labels (confusion matrix ticks, threshold
legend, top-feature-vs-target box plot ticks) also come from constructor
parameters -- positive_label/negative_label/unit_label -- rather than a
hardcoded domain. Defaults are generic ("Positive"/"Negative"/"record");
callers with a real domain (e.g. this project's Olist model in __main__
below) pass their own labels instead.

Styling contract (capstone handbook Section 11.2)
-------------------------------------------------
  * Style     : seaborn-v0_8-whitegrid
  * Palette   : muted professional (seaborn "muted" or custom hex palette)
  * Figure    : 10 × 6 inches
  * Resolution: 150 dpi minimum
  * Every chart: title, labelled axes, legend where applicable
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Optional

import matplotlib
matplotlib.use("Agg")  # non-interactive backend — safe for scripts and tests
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd
import seaborn as sns

from src.tools.audit_db import audit_logged
from src.tools.logging_config import get_agent_logger

logger = get_agent_logger("VisualizationAgent")

# ---------------------------------------------------------------------------
# Global style constants
# ---------------------------------------------------------------------------
_STYLE = "seaborn-v0_8-whitegrid"
_FIG_SIZE = (10, 6)
_DPI = 150
_PALETTE = sns.color_palette("muted")
_PRIMARY = _PALETTE[0]   # blue-ish
_ACCENT  = _PALETTE[1]   # orange-ish
_RED     = _PALETTE[3]   # muted red for "late"
_GREY    = "#a0a0a0"     # not distinguishable from no effect
_TITLE_SIZE = 14
_LABEL_SIZE = 11


# ---------------------------------------------------------------------------
# Report dataclass
# ---------------------------------------------------------------------------

@dataclass
class ChartRecord:
    """Metadata for a single generated chart."""
    name: str
    path: str
    description: str


@dataclass
class VisualizationReport:
    """Structured, JSON-serializable list of all generated charts."""
    charts: list = field(default_factory=list)
    skipped: list = field(default_factory=list)   # charts that were skipped + why

    def add(self, name: str, path: str, description: str) -> None:
        self.charts.append({"name": name, "path": path, "description": description})

    def skip(self, name: str, reason: str) -> None:
        self.skipped.append({"name": name, "reason": reason})
        logger.warning("Skipping chart '%s': %s", name, reason)

    def to_dict(self) -> dict:
        return {"charts": self.charts, "skipped": self.skipped}


# ---------------------------------------------------------------------------
# VisualizationAgent
# ---------------------------------------------------------------------------

class VisualizationAgent:
    """Generates all required dashboard and report charts from upstream
    EDA/ML report JSONs and the cleaned data CSV.

    Parameters
    ----------
    top_dist_features : int
        Number of numeric features to show distribution histograms for,
        selected by descending variance.
    top_importance_features : int
        Number of features to show in the feature importance bar chart.
    positive_label, negative_label : str
        What class 1 / class 0 are called in this business domain, used
        for binary classification chart labels (confusion matrix ticks,
        threshold-tradeoff legend, top-feature-vs-target box plot ticks).
        Defaults to generic "Positive" / "Negative" -- callers with a real
        domain (e.g. this project's Olist model) should pass their own
        labels rather than relying on these defaults.
    unit_label : str
        What one row is called in this business domain (e.g. "order",
        "house"). Defaults to generic "record".
    """

    def __init__(
        self,
        top_dist_features: int = 5,
        top_importance_features: int = 10,
        positive_label: str = "Positive",
        negative_label: str = "Negative",
        unit_label: str = "record",
    ):
        self.top_dist_features = top_dist_features
        self.top_importance_features = top_importance_features
        self.positive_label = positive_label
        self.negative_label = negative_label
        self.unit_label = unit_label
        self.report_: Optional[VisualizationReport] = None

    # ------------------------------------------------------------------
    # Chart 1 — Distribution histograms with KDE
    # ------------------------------------------------------------------

    def _chart_distributions(
        self,
        df: pd.DataFrame,
        feature_importances: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Histogram + KDE for top numeric features.

        Feature selection priority: feature_importances from the ML report
        (positive importances first, ordered descending). Falls back to
        highest-variance numeric columns when importances are absent.
        """
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        # Remove binary/target cols that aren't interesting to visualise
        numeric_cols = [c for c in numeric_cols if df[c].nunique() > 5]

        if feature_importances:
            # Take columns that actually exist in the cleaned data, in importance order
            ordered = [
                c for c in sorted(
                    feature_importances,
                    key=lambda f: feature_importances[f]["importance_mean"],
                    reverse=True,
                )
                if c in numeric_cols
            ]
            # Pad with high-variance columns if we don't have enough
            remaining = [c for c in numeric_cols if c not in ordered]
            remaining_sorted = sorted(remaining, key=lambda c: df[c].var(), reverse=True)
            cols = (ordered + remaining_sorted)[: self.top_dist_features]
        else:
            cols = sorted(numeric_cols, key=lambda c: df[c].var(), reverse=True)[
                : self.top_dist_features
            ]

        if not cols:
            report.skip("distributions", "No suitable numeric columns found")
            return

        with plt.style.context(_STYLE):
            n = len(cols)
            ncols = min(n, 2)
            nrows = (n + 1) // 2
            fig, axes = plt.subplots(nrows, ncols, figsize=(10, 4 * nrows))
            axes_flat = np.array(axes).flatten() if n > 1 else [axes]

            for i, col in enumerate(cols):
                ax = axes_flat[i]
                data = df[col].dropna()
                ax.hist(data, bins=40, color=_PRIMARY, alpha=0.6,
                        density=True, label="Histogram")
                try:
                    from scipy.stats import gaussian_kde
                    kde = gaussian_kde(data)
                    x_range = np.linspace(data.min(), data.max(), 300)
                    ax.plot(x_range, kde(x_range), color=_ACCENT,
                            linewidth=2, label="KDE")
                except Exception:
                    sns.kdeplot(data, ax=ax, color=_ACCENT, linewidth=2, label="KDE")
                ax.set_title(col, fontsize=_LABEL_SIZE, pad=6)
                ax.set_xlabel(col, fontsize=_LABEL_SIZE - 1)
                ax.set_ylabel("Density", fontsize=_LABEL_SIZE - 1)
                ax.legend(fontsize=9)

            # Hide any unused subplots
            for j in range(i + 1, len(axes_flat)):
                axes_flat[j].set_visible(False)

            fig.suptitle(
                f"Feature Distributions (top {len(cols)} by importance/variance)",
                fontsize=_TITLE_SIZE, y=1.01,
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "01_distributions.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add("distributions", path, f"Histogram + KDE for {cols}")
        logger.info("Saved distributions chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 2 — Correlation heatmap
    # ------------------------------------------------------------------

    def _chart_correlation_heatmap(
        self,
        corr_matrix: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        if not corr_matrix:
            report.skip("correlation_heatmap", "EDA report has no correlation matrix")
            return

        corr_df = pd.DataFrame(corr_matrix)

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            mask = np.zeros_like(corr_df.values, dtype=bool)
            np.fill_diagonal(mask, True)   # hide self-correlation diagonal
            sns.heatmap(
                corr_df,
                ax=ax,
                mask=mask,
                annot=True,
                fmt=".2f",
                annot_kws={"size": 7},
                cmap="RdBu_r",
                center=0,
                vmin=-1,
                vmax=1,
                linewidths=0.4,
                cbar_kws={"shrink": 0.8, "label": "Pearson r"},
            )
            ax.set_title("Numeric Feature Correlation Matrix", fontsize=_TITLE_SIZE, pad=12)
            ax.tick_params(axis="x", labelrotation=45, labelsize=8)
            ax.tick_params(axis="y", labelrotation=0, labelsize=8)
            fig.tight_layout()
            path = os.path.join(output_dir, "02_correlation_heatmap.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add("correlation_heatmap", path, "Pearson correlation matrix, annotated")
        logger.info("Saved correlation heatmap → %s", path)

    # ------------------------------------------------------------------
    # Chart 3 — Feature importance bar chart
    # ------------------------------------------------------------------

    def _chart_feature_importance(
        self,
        feature_importances: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        if not feature_importances:
            report.skip(
                "feature_importance",
                "ML report has no feature_importances (empty dict)",
            )
            return

        items = sorted(
            feature_importances.items(),
            key=lambda kv: kv[1]["importance_mean"], reverse=True,
        )
        items = items[: self.top_importance_features]
        names = [k for k, _ in items]
        means = [v["importance_mean"] for _, v in items]
        stds = [v["importance_std"] for _, v in items]
        distinguishable = [v["distinguishable_from_zero"] for _, v in items]

        # Color positive importances blue, negative red; features whose
        # mean +/- std range spans zero get a muted grey instead, since
        # their measured effect isn't distinguishable from no effect.
        colors = [
            _GREY if not dist else (_PRIMARY if m >= 0 else _RED)
            for m, dist in zip(means, distinguishable)
        ]

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            bars = ax.barh(
                names[::-1], means[::-1], xerr=stds[::-1], color=colors[::-1],
                edgecolor="white", linewidth=0.5,
                error_kw={"ecolor": "dimgrey", "elinewidth": 1, "capsize": 3},
            )
            ax.axvline(0, color="grey", linewidth=0.8, linestyle="--")
            ax.set_xlabel(
                "Permutation Importance (mean ± std across repeats)",
                fontsize=_LABEL_SIZE,
            )
            ax.set_ylabel("Feature", fontsize=_LABEL_SIZE)
            ax.set_title(
                f"Top {len(items)} Feature Importances (Permutation; grey = "
                "not distinguishable from no effect)",
                fontsize=_TITLE_SIZE, pad=10,
            )
            # Annotate each bar with its mean value
            for bar, val in zip(bars, means[::-1]):
                xpos = bar.get_width() + (0.0002 if val >= 0 else -0.0002)
                ha = "left" if val >= 0 else "right"
                ax.text(xpos, bar.get_y() + bar.get_height() / 2,
                        f"{val:.4f}", va="center", ha=ha, fontsize=8)
            fig.tight_layout()
            path = os.path.join(output_dir, "03_feature_importance.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "feature_importance", path,
            f"Top {len(items)} features by permutation importance",
        )
        logger.info("Saved feature importance chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 4 — Confusion matrix heatmap
    # ------------------------------------------------------------------

    def _chart_confusion_matrix(
        self,
        confusion_matrix: Optional[list],
        output_dir: str,
        report: VisualizationReport,
        task_type: str = "binary_classification",
    ) -> None:
        if not confusion_matrix:
            report.skip(
                "confusion_matrix",
                "ML report has no confusion matrix (regression task or absent)",
            )
            return

        cm = np.array(confusion_matrix)
        n_classes = cm.shape[0]
        labels = [str(i) for i in range(n_classes)]
        binary_labels = [f"{self.negative_label} (0)", f"{self.positive_label} (1)"]

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=(7, 6))
            sns.heatmap(
                cm,
                ax=ax,
                annot=True,
                fmt="d",
                annot_kws={"size": 14, "weight": "bold"},
                cmap="Blues",
                xticklabels=binary_labels if n_classes == 2 else labels,
                yticklabels=binary_labels if n_classes == 2 else labels,
                linewidths=0.5,
                cbar_kws={"label": "Count"},
            )
            ax.set_xlabel("Predicted label", fontsize=_LABEL_SIZE)
            ax.set_ylabel("True label", fontsize=_LABEL_SIZE)
            ax.set_title(
                "Confusion Matrix (threshold = 0.50)", fontsize=_TITLE_SIZE, pad=10
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "04_confusion_matrix.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "confusion_matrix", path, "Confusion matrix at default threshold 0.5"
        )
        logger.info("Saved confusion matrix → %s", path)

    # ------------------------------------------------------------------
    # Chart 5 — Threshold tradeoff line chart
    # ------------------------------------------------------------------

    def _chart_threshold_tradeoff(
        self,
        threshold_metrics: Optional[list],
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        if not threshold_metrics:
            report.skip(
                "threshold_tradeoff",
                "ML report has no threshold_metrics (regression task or absent)",
            )
            return

        thresholds = [t["threshold"] for t in threshold_metrics]
        recall = [t["recall_minority"] for t in threshold_metrics]
        precision = [t["precision_minority"] for t in threshold_metrics]
        f1 = [t["f1_macro"] for t in threshold_metrics]

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            ax.plot(thresholds, recall, marker="o", linewidth=2,
                    color=_PRIMARY, label=f"{self.positive_label} Recall")
            ax.plot(thresholds, precision, marker="s", linewidth=2,
                    color=_RED, label=f"{self.positive_label} Precision")
            ax.plot(thresholds, f1, marker="^", linewidth=2,
                    linestyle="--", color=_ACCENT, label="F1-macro")

            for t, r, p in zip(thresholds, recall, precision):
                ax.annotate(f"{r:.2f}", (t, r), textcoords="offset points",
                            xytext=(6, 4), fontsize=9, color=_PRIMARY)
                ax.annotate(f"{p:.2f}", (t, p), textcoords="offset points",
                            xytext=(6, -12), fontsize=9, color=_RED)

            ax.set_xlabel("Decision Threshold", fontsize=_LABEL_SIZE)
            ax.set_ylabel("Score", fontsize=_LABEL_SIZE)
            ax.set_title(
                "Precision / Recall Tradeoff Across Decision Thresholds\n"
                f"(minority class = {self.positive_label})",
                fontsize=_TITLE_SIZE, pad=10,
            )
            ax.set_xticks(thresholds)
            ax.set_ylim(0, 1.05)
            ax.legend(fontsize=_LABEL_SIZE - 1)
            fig.tight_layout()
            path = os.path.join(output_dir, "05_threshold_tradeoff.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "threshold_tradeoff", path,
            "Minority-class precision and recall across decision thresholds",
        )
        logger.info("Saved threshold tradeoff chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 7 — Calibration curve (reliability diagram)
    # ------------------------------------------------------------------

    def _chart_calibration_curve(
        self,
        calibration: Optional[dict],
        calibrated_comparison: Optional[dict],
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Reliability diagram: mean predicted probability per bin (x) vs.
        observed frequency of the positive class in that bin (y), against
        the y=x "perfectly calibrated" reference line. Overlays a
        CalibratedClassifierCV comparison curve when the ML report
        includes one (i.e. the raw model's ECE exceeded the miscalibration
        threshold -- see MLAgent._maybe_calibrate)."""
        if not calibration or not calibration.get("prob_pred"):
            report.skip(
                "calibration_curve",
                "ML report has no calibration data (regression/multiclass task, "
                "no predict_proba, or absent)",
            )
            return

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            ax.plot(
                [0, 1], [0, 1], color="grey", linewidth=1.5, linestyle="--",
                label="Perfectly calibrated",
            )
            ax.plot(
                calibration["prob_pred"], calibration["prob_true"],
                marker="o", linewidth=2, color=_PRIMARY,
                label=f"Raw model (ECE={calibration.get('ece', 0):.3f})",
            )
            if calibrated_comparison and calibrated_comparison.get("prob_pred"):
                method = calibrated_comparison.get("method", "calibrated")
                ax.plot(
                    calibrated_comparison["prob_pred"], calibrated_comparison["prob_true"],
                    marker="s", linewidth=2, linestyle=":", color=_ACCENT,
                    label=f"{method.title()}-calibrated (ECE={calibrated_comparison.get('ece', 0):.3f})",
                )

            ax.set_xlabel("Mean predicted probability", fontsize=_LABEL_SIZE)
            ax.set_ylabel("Observed frequency of positive class", fontsize=_LABEL_SIZE)
            ax.set_title(
                "Calibration Curve (Reliability Diagram)\n"
                "class_weight='balanced' shifts raw probabilities — read decision "
                "thresholds as cutoffs, not literal probabilities",
                fontsize=_TITLE_SIZE - 2, pad=10,
            )
            ax.set_xlim(-0.02, 1.02)
            ax.set_ylim(-0.02, 1.02)
            ax.legend(fontsize=_LABEL_SIZE - 1, loc="upper left")
            fig.tight_layout()
            path = os.path.join(output_dir, "07_calibration_curve.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "calibration_curve", path,
            "Reliability diagram: predicted probability vs. observed frequency",
        )
        logger.info("Saved calibration curve chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 4 (regression variant) — Actual vs. predicted scatter
    # ------------------------------------------------------------------

    def _chart_actual_vs_predicted(
        self,
        test_predictions: Optional[dict],
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Regression counterpart to the confusion-matrix heatmap.

        Plots the model's held-out predictions against the true values,
        with a diagonal reference line marking perfect prediction. Points
        hugging the diagonal indicate accurate predictions; systematic
        deviation above/below it indicates over-/under-prediction.
        """
        if not test_predictions or not test_predictions.get("actual") or not test_predictions.get("predicted"):
            report.skip(
                "actual_vs_predicted",
                "ML report has no test_predictions (classification task or absent)",
            )
            return

        actual = np.array(test_predictions["actual"])
        predicted = np.array(test_predictions["predicted"])

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            ax.scatter(
                actual, predicted, color=_PRIMARY, alpha=0.4,
                edgecolor="white", linewidth=0.3, s=20,
            )

            lo = float(min(actual.min(), predicted.min()))
            hi = float(max(actual.max(), predicted.max()))
            ax.plot(
                [lo, hi], [lo, hi], color=_RED, linewidth=2,
                linestyle="--", label="Perfect prediction",
            )

            ax.set_xlabel("Actual value", fontsize=_LABEL_SIZE)
            ax.set_ylabel("Predicted value", fontsize=_LABEL_SIZE)
            ax.set_title(
                "Actual vs. Predicted (held-out test set)",
                fontsize=_TITLE_SIZE, pad=10,
            )
            ax.legend(fontsize=_LABEL_SIZE - 1)
            fig.tight_layout()
            path = os.path.join(output_dir, "04_actual_vs_predicted.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "actual_vs_predicted", path,
            "Predicted vs. actual values on the held-out test set",
        )
        logger.info("Saved actual-vs-predicted chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 5 (regression variant) — Residual plot
    # ------------------------------------------------------------------

    def _chart_residuals(
        self,
        test_predictions: Optional[dict],
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Regression counterpart to the threshold-tradeoff chart.

        Plots residuals (actual - predicted) against the predicted value,
        with a horizontal zero-error line. A random scatter around zero
        indicates a well-specified model; a visible pattern (funnel,
        curve, trend) indicates the model is systematically wrong in some
        region of the prediction range.
        """
        if not test_predictions or not test_predictions.get("actual") or not test_predictions.get("predicted"):
            report.skip(
                "residuals",
                "ML report has no test_predictions (classification task or absent)",
            )
            return

        actual = np.array(test_predictions["actual"])
        predicted = np.array(test_predictions["predicted"])
        residuals = actual - predicted

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            ax.scatter(
                predicted, residuals, color=_PRIMARY, alpha=0.4,
                edgecolor="white", linewidth=0.3, s=20,
            )
            ax.axhline(0, color=_RED, linewidth=2, linestyle="--", label="Zero error")

            ax.set_xlabel("Predicted value", fontsize=_LABEL_SIZE)
            ax.set_ylabel("Residual (actual - predicted)", fontsize=_LABEL_SIZE)
            ax.set_title(
                "Residual Plot (held-out test set)", fontsize=_TITLE_SIZE, pad=10
            )
            ax.legend(fontsize=_LABEL_SIZE - 1)
            fig.tight_layout()
            path = os.path.join(output_dir, "05_residuals.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "residuals", path,
            "Residuals (actual - predicted) vs. predicted value",
        )
        logger.info("Saved residuals chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 6 — Top feature vs. target (box plot for classification,
    # scatter for regression)
    # ------------------------------------------------------------------

    def _chart_top_feature_vs_target(
        self,
        df: pd.DataFrame,
        target_col: str,
        feature_importances: dict,
        output_dir: str,
        report: VisualizationReport,
        task_type: str = "binary_classification",
    ) -> None:
        if not feature_importances:
            report.skip(
                "top_feature_vs_target",
                "No feature importances available; cannot select top feature",
            )
            return

        if target_col not in df.columns:
            report.skip(
                "top_feature_vs_target",
                f"Target column '{target_col}' not found in data",
            )
            return

        # Pick the highest-importance feature that is numeric and in the data
        numeric_cols = set(df.select_dtypes(include=[np.number]).columns)
        top_feature = None
        for feat in sorted(
            feature_importances,
            key=lambda f: feature_importances[f]["importance_mean"], reverse=True,
        ):
            if feat in numeric_cols and feat != target_col:
                top_feature = feat
                break

        if top_feature is None:
            report.skip(
                "top_feature_vs_target",
                "No numeric top-importance feature found in data",
            )
            return

        if task_type == "regression":
            self._render_top_feature_vs_target_scatter(df, target_col, top_feature, output_dir, report)
        else:
            self._render_top_feature_vs_target_boxplot(df, target_col, top_feature, output_dir, report)

    def _render_top_feature_vs_target_boxplot(
        self,
        df: pd.DataFrame,
        target_col: str,
        top_feature: str,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Classification variant: box plot of the top feature split by class.

        Binary 0/1 targets get concrete tick labels from self.negative_label
        / self.positive_label (e.g. "On-time (0)" / "Late (1)" for this
        project's Olist model) rather than bare "0"/"1" -- multiclass
        targets fall back to the class values themselves, since a fixed
        pair of labels can't describe more than two classes.
        """
        target_values = sorted(df[target_col].dropna().unique())
        palette = {v: (_PRIMARY if i == 0 else _RED) for i, v in enumerate(target_values)}

        order = [str(v) for v in target_values]
        tick_labels = (
            [f"{self.negative_label} (0)", f"{self.positive_label} (1)"]
            if set(target_values) <= {0, 1} and len(target_values) == 2
            else order
        )

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            plot_df = df[[target_col, top_feature]].dropna().copy()
            plot_df[target_col] = plot_df[target_col].astype(str)

            pal = {str(k): v for k, v in palette.items()}

            sns.boxplot(
                data=plot_df,
                x=target_col,
                y=top_feature,
                hue=target_col,
                order=order,
                palette=pal,
                legend=False,
                ax=ax,
                width=0.5,
                flierprops={"marker": ".", "markersize": 3, "alpha": 0.3},
            )
            ax.set_xticks(range(len(order)))
            ax.set_xticklabels(tick_labels, fontsize=_LABEL_SIZE)
            ax.set_xlabel(f"{self.unit_label.capitalize()} outcome", fontsize=_LABEL_SIZE)
            ax.set_ylabel(top_feature, fontsize=_LABEL_SIZE)
            ax.set_title(
                f"Distribution of '{top_feature}'\nby {self.unit_label.capitalize()} Outcome",
                fontsize=_TITLE_SIZE, pad=10,
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "06_top_feature_vs_target.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "top_feature_vs_target", path,
            f"Box plot of '{top_feature}' split by {target_col}",
        )
        logger.info("Saved top-feature vs. target box plot → %s", path)

    def _render_top_feature_vs_target_scatter(
        self,
        df: pd.DataFrame,
        target_col: str,
        top_feature: str,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Regression variant: scatter of the top feature vs. the continuous target."""
        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            plot_df = df[[target_col, top_feature]].dropna()

            ax.scatter(
                plot_df[top_feature], plot_df[target_col], color=_PRIMARY,
                alpha=0.4, edgecolor="white", linewidth=0.3, s=20,
            )

            if len(plot_df) >= 2:
                coeffs = np.polyfit(plot_df[top_feature], plot_df[target_col], 1)
                x_range = np.linspace(plot_df[top_feature].min(), plot_df[top_feature].max(), 100)
                ax.plot(
                    x_range, np.polyval(coeffs, x_range), color=_RED,
                    linewidth=2, linestyle="--", label="Linear trend",
                )
                ax.legend(fontsize=_LABEL_SIZE - 1)

            ax.set_xlabel(top_feature, fontsize=_LABEL_SIZE)
            ax.set_ylabel(target_col, fontsize=_LABEL_SIZE)
            ax.set_title(
                f"'{top_feature}' vs. '{target_col}'",
                fontsize=_TITLE_SIZE, pad=10,
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "06_top_feature_vs_target.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "top_feature_vs_target", path,
            f"Scatter plot of '{top_feature}' vs. continuous target '{target_col}'",
        )
        logger.info("Saved top-feature vs. target scatter → %s", path)

    # ------------------------------------------------------------------
    # Chart 8 — Error rate by segment (handbook F6)
    # ------------------------------------------------------------------

    def _chart_error_by_segment(
        self,
        error_analysis: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Bar chart of error rate/MAE per segment value, for the first 1-2
        columns in error_analysis["segment_columns"] -- already ordered by
        the ML agent (higher cardinality first, see _detect_segment_columns),
        so "top" here just means "first N of that list", not a fresh
        ranking. A dashed reference line marks the overall rate/MAE so a
        segment's deviation is visible at a glance. Segment axis, metric,
        and even how many panels to draw are all read from the report --
        nothing here is specific to this project's columns.
        """
        segment_cols = error_analysis.get("segment_columns") or []
        segments = error_analysis.get("segments") or {}
        overall = error_analysis.get("overall") or {}
        task_type = error_analysis.get("task_type", "binary_classification")

        cols_to_plot = [c for c in segment_cols[:2] if segments.get(c)]
        if not cols_to_plot:
            report.skip(
                "error_by_segment",
                "ML report has no error_analysis segments to plot",
            )
            return

        with plt.style.context(_STYLE):
            fig, axes = plt.subplots(
                1, len(cols_to_plot), figsize=(7 * len(cols_to_plot), 5.5), squeeze=False,
            )
            axes_flat = axes[0]

            for ax, col in zip(axes_flat, cols_to_plot):
                rows = segments[col]
                x = np.arange(len(rows))
                elevated = [
                    any(v is True for k, v in r.items() if k.startswith("elevated_"))
                    for r in rows
                ]
                labels = [
                    f"{r['segment_value']}{'*' if flag else ''}"
                    for r, flag in zip(rows, elevated)
                ]

                if task_type == "binary_classification":
                    width = 0.35
                    fn = [r["false_negative_rate"] or 0 for r in rows]
                    fp = [r["false_positive_rate"] or 0 for r in rows]
                    ax.bar(x - width / 2, fn, width, color=_RED, label="False negative rate")
                    ax.bar(x + width / 2, fp, width, color=_PRIMARY, label="False positive rate")
                    if overall.get("false_negative_rate") is not None:
                        ax.axhline(overall["false_negative_rate"], color=_RED,
                                   linestyle="--", linewidth=1.3, label="Overall FN rate")
                    if overall.get("false_positive_rate") is not None:
                        ax.axhline(overall["false_positive_rate"], color=_PRIMARY,
                                   linestyle=":", linewidth=1.3, label="Overall FP rate")
                    ax.set_ylabel("Error rate", fontsize=_LABEL_SIZE)
                elif task_type == "multiclass_classification":
                    rate = [r["misclassification_rate"] for r in rows]
                    ax.bar(x, rate, color=_PRIMARY, label="Misclassification rate")
                    if overall.get("misclassification_rate") is not None:
                        ax.axhline(overall["misclassification_rate"], color=_RED,
                                   linestyle="--", linewidth=1.3, label="Overall rate")
                    ax.set_ylabel("Misclassification rate", fontsize=_LABEL_SIZE)
                else:  # regression
                    mae = [r["mae"] for r in rows]
                    ax.bar(x, mae, color=_PRIMARY, label="MAE")
                    if overall.get("mae") is not None:
                        ax.axhline(overall["mae"], color=_RED,
                                   linestyle="--", linewidth=1.3, label="Overall MAE")
                    ax.set_ylabel("MAE", fontsize=_LABEL_SIZE)

                ax.set_xticks(x)
                ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=8)
                ax.set_xlabel(
                    f"{col} (encoded segment value; * = elevated error)",
                    fontsize=_LABEL_SIZE - 1,
                )
                ax.set_title(col, fontsize=_TITLE_SIZE - 1)
                ax.legend(fontsize=8)

            fig.suptitle(
                "Error Rate by Segment -- an association observed in held-out "
                "predictions, not a causal claim about why segments differ",
                fontsize=_TITLE_SIZE - 1, y=1.02,
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "08_error_by_segment.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "error_by_segment", path,
            f"Error rate by segment for {cols_to_plot}",
        )
        logger.info("Saved error-by-segment chart → %s", path)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    @audit_logged(
        "VisualizationAgent",
        input_arg=("eda_report_path", "ml_report_path", "cleaned_data_path"),
    )
    def run(
        self,
        eda_report_path: str,
        ml_report_path: str,
        cleaned_data_path: str,
        target_col: str = "is_late_delivery",
        output_dir: str = "workspace/visualizations",
    ) -> tuple[bool, str]:
        """Generate all charts from the EDA report, ML report, and cleaned data.

        Parameters
        ----------
        eda_report_path : str
            Path to the EDA agent's JSON report.
        ml_report_path : str
            Path to the ML agent's JSON report.
        cleaned_data_path : str
            Path to the cleaned (pre-feature-engineering) CSV, used for
            distribution histograms and the box plot.
        target_col : str
            Name of the prediction target column in cleaned_data_path.
        output_dir : str
            Directory where PNG files and the visualization report are written.

        Returns
        -------
        (success, report_path_or_error_message)
        """
        logger.info(
            "Starting visualization run  eda=%s  ml=%s  data=%s  out=%s",
            eda_report_path, ml_report_path, cleaned_data_path, output_dir,
        )

        os.makedirs(output_dir, exist_ok=True)
        report = VisualizationReport()

        # --- Load EDA report ---
        eda = {}
        try:
            with open(eda_report_path) as f:
                eda = json.load(f)
        except Exception as exc:
            logger.warning("Could not load EDA report: %s", exc)

        # --- Load ML report ---
        ml = {}
        try:
            with open(ml_report_path) as f:
                ml = json.load(f)
        except Exception as exc:
            logger.warning("Could not load ML report: %s", exc)

        # --- Load cleaned data ---
        df = pd.DataFrame()
        try:
            df = pd.read_csv(cleaned_data_path)
            logger.info("Loaded data: %s", df.shape)
        except Exception as exc:
            logger.warning("Could not load cleaned data: %s", exc)

        feature_importances: dict = ml.get("feature_importances") or {}
        corr_matrix: dict = eda.get("correlation_matrix") or {}
        confusion_matrix = ml.get("confusion_matrix")
        threshold_metrics = ml.get("threshold_metrics")
        test_predictions = ml.get("test_predictions")
        calibration = ml.get("calibration")
        calibrated_comparison = ml.get("calibrated_comparison")
        error_analysis: dict = ml.get("error_analysis") or {}
        task_type: str = ml.get("task_type", "binary_classification")

        # --- Generate charts ---
        self._chart_distributions(df, feature_importances, output_dir, report)
        self._chart_correlation_heatmap(corr_matrix, output_dir, report)
        self._chart_feature_importance(feature_importances, output_dir, report)

        if task_type == "regression":
            self._chart_actual_vs_predicted(test_predictions, output_dir, report)
            self._chart_residuals(test_predictions, output_dir, report)
        else:
            self._chart_confusion_matrix(confusion_matrix, output_dir, report, task_type)
            self._chart_threshold_tradeoff(threshold_metrics, output_dir, report)
            self._chart_calibration_curve(calibration, calibrated_comparison, output_dir, report)

        self._chart_top_feature_vs_target(
            df, target_col, feature_importances, output_dir, report, task_type=task_type
        )

        self._chart_error_by_segment(error_analysis, output_dir, report)

        self.report_ = report

        report_path = os.path.join(output_dir, "visualization_report.json")
        with open(report_path, "w") as f:
            json.dump(report.to_dict(), f, indent=2)
        logger.info(
            "Visualization complete: %d charts generated, %d skipped",
            len(report.charts), len(report.skipped),
        )
        logger.info("Visualization report written to %s", report_path)

        return True, report_path


if __name__ == "__main__":
    import sys

    # This project's model always predicts one concrete thing: whether an
    # ORDER will be a LATE DELIVERY. Passed explicitly here rather than
    # relying on VisualizationAgent's generic defaults (see class
    # docstring) -- the agent itself is domain-agnostic.
    agent = VisualizationAgent(
        positive_label="Late",
        negative_label="On-time",
        unit_label="order",
    )
    success, result = agent.run(
        eda_report_path="data/processed/olist_flattened_cleaned_eda_report.json",
        ml_report_path="data/processed/olist_flattened_cleaned_features_ml_report.json",
        cleaned_data_path="data/processed/olist_flattened_cleaned.csv",
        output_dir="workspace/visualizations",
    )
    if success:
        print(f"Success. Report at: {result}")
        for chart in agent.report_.charts:
            size_kb = os.path.getsize(chart["path"]) // 1024
            print(f"  {chart['name']:35s}  {size_kb:>5} KB  {chart['path']}")
    else:
        print(f"Failed: {result}")
        sys.exit(1)
