"""
src/agents/visualizer.py

Visualization Agent.

Responsibilities (per the capstone handbook, Section 11.3): consume the
EDA report, ML report, and cleaned data to produce the chart images used
in the dashboard and final PDF report.

Design note: like the preceding agents this is fully deterministic — pure
matplotlib/seaborn, no LLM calls. Each chart is generated by a dedicated
private method so it can be unit-tested in isolation. The agent handles
missing/incomplete upstream reports gracefully: if a required piece of data
is absent (e.g. empty feature_importances) the relevant chart is skipped
and logged as a warning rather than crashing.

Styling contract (capstone handbook Section 11.2)
-------------------------------------------------
  * Style     : seaborn-v0_8-whitegrid
  * Palette   : muted professional (seaborn "muted" or custom hex palette)
  * Figure    : 10 × 6 inches
  * Resolution: 150 dpi minimum
  * Every chart: title, labelled axes, legend where applicable
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Optional

import matplotlib
matplotlib.use("Agg")  # non-interactive backend — safe for scripts and tests
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd
import seaborn as sns

from src.tools.logging_config import get_agent_logger

logger = get_agent_logger("VisualizationAgent")

# ---------------------------------------------------------------------------
# Global style constants
# ---------------------------------------------------------------------------
_STYLE = "seaborn-v0_8-whitegrid"
_FIG_SIZE = (10, 6)
_DPI = 150
_PALETTE = sns.color_palette("muted")
_PRIMARY = _PALETTE[0]   # blue-ish
_ACCENT  = _PALETTE[1]   # orange-ish
_RED     = _PALETTE[3]   # muted red for "late"
_TITLE_SIZE = 14
_LABEL_SIZE = 11


# ---------------------------------------------------------------------------
# Report dataclass
# ---------------------------------------------------------------------------

@dataclass
class ChartRecord:
    """Metadata for a single generated chart."""
    name: str
    path: str
    description: str


@dataclass
class VisualizationReport:
    """Structured, JSON-serializable list of all generated charts."""
    charts: list = field(default_factory=list)
    skipped: list = field(default_factory=list)   # charts that were skipped + why

    def add(self, name: str, path: str, description: str) -> None:
        self.charts.append({"name": name, "path": path, "description": description})

    def skip(self, name: str, reason: str) -> None:
        self.skipped.append({"name": name, "reason": reason})
        logger.warning("Skipping chart '%s': %s", name, reason)

    def to_dict(self) -> dict:
        return {"charts": self.charts, "skipped": self.skipped}


# ---------------------------------------------------------------------------
# VisualizationAgent
# ---------------------------------------------------------------------------

class VisualizationAgent:
    """Generates all required dashboard and report charts from upstream
    EDA/ML report JSONs and the cleaned data CSV.

    Parameters
    ----------
    top_dist_features : int
        Number of numeric features to show distribution histograms for,
        selected by descending variance.
    top_importance_features : int
        Number of features to show in the feature importance bar chart.
    """

    def __init__(
        self,
        top_dist_features: int = 5,
        top_importance_features: int = 10,
    ):
        self.top_dist_features = top_dist_features
        self.top_importance_features = top_importance_features
        self.report_: Optional[VisualizationReport] = None

    # ------------------------------------------------------------------
    # Chart 1 — Distribution histograms with KDE
    # ------------------------------------------------------------------

    def _chart_distributions(
        self,
        df: pd.DataFrame,
        feature_importances: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        """Histogram + KDE for top numeric features.

        Feature selection priority: feature_importances from the ML report
        (positive importances first, ordered descending). Falls back to
        highest-variance numeric columns when importances are absent.
        """
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        # Remove binary/target cols that aren't interesting to visualise
        numeric_cols = [c for c in numeric_cols if df[c].nunique() > 5]

        if feature_importances:
            # Take columns that actually exist in the cleaned data, in importance order
            ordered = [
                c for c in sorted(feature_importances, key=feature_importances.__getitem__, reverse=True)
                if c in numeric_cols
            ]
            # Pad with high-variance columns if we don't have enough
            remaining = [c for c in numeric_cols if c not in ordered]
            remaining_sorted = sorted(remaining, key=lambda c: df[c].var(), reverse=True)
            cols = (ordered + remaining_sorted)[: self.top_dist_features]
        else:
            cols = sorted(numeric_cols, key=lambda c: df[c].var(), reverse=True)[
                : self.top_dist_features
            ]

        if not cols:
            report.skip("distributions", "No suitable numeric columns found")
            return

        with plt.style.context(_STYLE):
            n = len(cols)
            ncols = min(n, 2)
            nrows = (n + 1) // 2
            fig, axes = plt.subplots(nrows, ncols, figsize=(10, 4 * nrows))
            axes_flat = np.array(axes).flatten() if n > 1 else [axes]

            for i, col in enumerate(cols):
                ax = axes_flat[i]
                data = df[col].dropna()
                ax.hist(data, bins=40, color=_PRIMARY, alpha=0.6,
                        density=True, label="Histogram")
                try:
                    from scipy.stats import gaussian_kde
                    kde = gaussian_kde(data)
                    x_range = np.linspace(data.min(), data.max(), 300)
                    ax.plot(x_range, kde(x_range), color=_ACCENT,
                            linewidth=2, label="KDE")
                except Exception:
                    sns.kdeplot(data, ax=ax, color=_ACCENT, linewidth=2, label="KDE")
                ax.set_title(col, fontsize=_LABEL_SIZE, pad=6)
                ax.set_xlabel(col, fontsize=_LABEL_SIZE - 1)
                ax.set_ylabel("Density", fontsize=_LABEL_SIZE - 1)
                ax.legend(fontsize=9)

            # Hide any unused subplots
            for j in range(i + 1, len(axes_flat)):
                axes_flat[j].set_visible(False)

            fig.suptitle(
                f"Feature Distributions (top {len(cols)} by importance/variance)",
                fontsize=_TITLE_SIZE, y=1.01,
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "01_distributions.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add("distributions", path, f"Histogram + KDE for {cols}")
        logger.info("Saved distributions chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 2 — Correlation heatmap
    # ------------------------------------------------------------------

    def _chart_correlation_heatmap(
        self,
        corr_matrix: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        if not corr_matrix:
            report.skip("correlation_heatmap", "EDA report has no correlation matrix")
            return

        corr_df = pd.DataFrame(corr_matrix)

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            mask = np.zeros_like(corr_df.values, dtype=bool)
            np.fill_diagonal(mask, True)   # hide self-correlation diagonal
            sns.heatmap(
                corr_df,
                ax=ax,
                mask=mask,
                annot=True,
                fmt=".2f",
                annot_kws={"size": 7},
                cmap="RdBu_r",
                center=0,
                vmin=-1,
                vmax=1,
                linewidths=0.4,
                cbar_kws={"shrink": 0.8, "label": "Pearson r"},
            )
            ax.set_title("Numeric Feature Correlation Matrix", fontsize=_TITLE_SIZE, pad=12)
            ax.tick_params(axis="x", labelrotation=45, labelsize=8)
            ax.tick_params(axis="y", labelrotation=0, labelsize=8)
            fig.tight_layout()
            path = os.path.join(output_dir, "02_correlation_heatmap.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add("correlation_heatmap", path, "Pearson correlation matrix, annotated")
        logger.info("Saved correlation heatmap → %s", path)

    # ------------------------------------------------------------------
    # Chart 3 — Feature importance bar chart
    # ------------------------------------------------------------------

    def _chart_feature_importance(
        self,
        feature_importances: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        if not feature_importances:
            report.skip(
                "feature_importance",
                "ML report has no feature_importances (empty dict)",
            )
            return

        items = sorted(feature_importances.items(), key=lambda x: x[1], reverse=True)
        items = items[: self.top_importance_features]
        names = [k for k, _ in items]
        values = [v for _, v in items]

        # Color positive importances blue, negative red
        colors = [_PRIMARY if v >= 0 else _RED for v in values]

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            bars = ax.barh(names[::-1], values[::-1], color=colors[::-1],
                           edgecolor="white", linewidth=0.5)
            ax.axvline(0, color="grey", linewidth=0.8, linestyle="--")
            ax.set_xlabel("Permutation Importance", fontsize=_LABEL_SIZE)
            ax.set_ylabel("Feature", fontsize=_LABEL_SIZE)
            ax.set_title(
                f"Top {len(items)} Feature Importances (Permutation)",
                fontsize=_TITLE_SIZE, pad=10,
            )
            # Annotate each bar with its value
            for bar, val in zip(bars, values[::-1]):
                xpos = bar.get_width() + (0.0002 if val >= 0 else -0.0002)
                ha = "left" if val >= 0 else "right"
                ax.text(xpos, bar.get_y() + bar.get_height() / 2,
                        f"{val:.4f}", va="center", ha=ha, fontsize=8)
            fig.tight_layout()
            path = os.path.join(output_dir, "03_feature_importance.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "feature_importance", path,
            f"Top {len(items)} features by permutation importance",
        )
        logger.info("Saved feature importance chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 4 — Confusion matrix heatmap
    # ------------------------------------------------------------------

    def _chart_confusion_matrix(
        self,
        confusion_matrix: Optional[list],
        output_dir: str,
        report: VisualizationReport,
        task_type: str = "binary_classification",
    ) -> None:
        if not confusion_matrix:
            report.skip(
                "confusion_matrix",
                "ML report has no confusion matrix (regression task or absent)",
            )
            return

        cm = np.array(confusion_matrix)
        n_classes = cm.shape[0]
        labels = [str(i) for i in range(n_classes)]

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=(7, 6))
            sns.heatmap(
                cm,
                ax=ax,
                annot=True,
                fmt="d",
                annot_kws={"size": 14, "weight": "bold"},
                cmap="Blues",
                xticklabels=["On-time (0)", "Late (1)"] if n_classes == 2 else labels,
                yticklabels=["On-time (0)", "Late (1)"] if n_classes == 2 else labels,
                linewidths=0.5,
                cbar_kws={"label": "Count"},
            )
            ax.set_xlabel("Predicted label", fontsize=_LABEL_SIZE)
            ax.set_ylabel("True label", fontsize=_LABEL_SIZE)
            ax.set_title(
                "Confusion Matrix (threshold = 0.50)", fontsize=_TITLE_SIZE, pad=10
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "04_confusion_matrix.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "confusion_matrix", path, "Confusion matrix at default threshold 0.5"
        )
        logger.info("Saved confusion matrix → %s", path)

    # ------------------------------------------------------------------
    # Chart 5 — Threshold tradeoff line chart
    # ------------------------------------------------------------------

    def _chart_threshold_tradeoff(
        self,
        threshold_metrics: Optional[list],
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        if not threshold_metrics:
            report.skip(
                "threshold_tradeoff",
                "ML report has no threshold_metrics (regression task or absent)",
            )
            return

        thresholds = [t["threshold"] for t in threshold_metrics]
        recall = [t["recall_minority"] for t in threshold_metrics]
        precision = [t["precision_minority"] for t in threshold_metrics]
        f1 = [t["f1_macro"] for t in threshold_metrics]

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            ax.plot(thresholds, recall, marker="o", linewidth=2,
                    color=_PRIMARY, label="Minority Recall (late detected)")
            ax.plot(thresholds, precision, marker="s", linewidth=2,
                    color=_RED, label="Minority Precision")
            ax.plot(thresholds, f1, marker="^", linewidth=2,
                    linestyle="--", color=_ACCENT, label="F1-macro")

            for t, r, p in zip(thresholds, recall, precision):
                ax.annotate(f"{r:.2f}", (t, r), textcoords="offset points",
                            xytext=(6, 4), fontsize=9, color=_PRIMARY)
                ax.annotate(f"{p:.2f}", (t, p), textcoords="offset points",
                            xytext=(6, -12), fontsize=9, color=_RED)

            ax.set_xlabel("Decision Threshold", fontsize=_LABEL_SIZE)
            ax.set_ylabel("Score", fontsize=_LABEL_SIZE)
            ax.set_title(
                "Precision / Recall Tradeoff Across Decision Thresholds\n"
                "(minority class = late delivery)",
                fontsize=_TITLE_SIZE, pad=10,
            )
            ax.set_xticks(thresholds)
            ax.set_ylim(0, 1.05)
            ax.legend(fontsize=_LABEL_SIZE - 1)
            fig.tight_layout()
            path = os.path.join(output_dir, "05_threshold_tradeoff.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "threshold_tradeoff", path,
            "Minority-class precision and recall across decision thresholds",
        )
        logger.info("Saved threshold tradeoff chart → %s", path)

    # ------------------------------------------------------------------
    # Chart 6 — Box plot: top feature vs. target
    # ------------------------------------------------------------------

    def _chart_top_feature_vs_target(
        self,
        df: pd.DataFrame,
        target_col: str,
        feature_importances: dict,
        output_dir: str,
        report: VisualizationReport,
    ) -> None:
        if not feature_importances:
            report.skip(
                "top_feature_vs_target",
                "No feature importances available; cannot select top feature",
            )
            return

        if target_col not in df.columns:
            report.skip(
                "top_feature_vs_target",
                f"Target column '{target_col}' not found in data",
            )
            return

        # Pick the highest-importance feature that is numeric and in the data
        numeric_cols = set(df.select_dtypes(include=[np.number]).columns)
        top_feature = None
        for feat in sorted(feature_importances, key=feature_importances.__getitem__, reverse=True):
            if feat in numeric_cols and feat != target_col:
                top_feature = feat
                break

        if top_feature is None:
            report.skip(
                "top_feature_vs_target",
                "No numeric top-importance feature found in data",
            )
            return

        target_values = sorted(df[target_col].dropna().unique())
        palette = {v: (_PRIMARY if i == 0 else _RED) for i, v in enumerate(target_values)}
        labels = {v: f"On-time ({v})" if v == 0 else f"Late ({v})"
                  for v in target_values} if set(target_values) <= {0, 1} else None

        with plt.style.context(_STYLE):
            fig, ax = plt.subplots(figsize=_FIG_SIZE)
            plot_df = df[[target_col, top_feature]].dropna().copy()
            plot_df[target_col] = plot_df[target_col].astype(str)

            order = [str(v) for v in target_values]
            pal = {str(k): v for k, v in palette.items()}
            tick_labels = (
                [labels[v] for v in target_values] if labels else order
            )

            sns.boxplot(
                data=plot_df,
                x=target_col,
                y=top_feature,
                hue=target_col,
                order=order,
                palette=pal,
                legend=False,
                ax=ax,
                width=0.5,
                flierprops={"marker": ".", "markersize": 3, "alpha": 0.3},
            )
            ax.set_xticks(range(len(tick_labels)))
            ax.set_xticklabels(tick_labels, fontsize=_LABEL_SIZE)
            ax.set_xlabel("Delivery outcome", fontsize=_LABEL_SIZE)
            ax.set_ylabel(top_feature, fontsize=_LABEL_SIZE)
            ax.set_title(
                f"Distribution of '{top_feature}'\nby Delivery Outcome",
                fontsize=_TITLE_SIZE, pad=10,
            )
            fig.tight_layout()
            path = os.path.join(output_dir, "06_top_feature_vs_target.png")
            fig.savefig(path, dpi=_DPI, bbox_inches="tight")
            plt.close(fig)

        report.add(
            "top_feature_vs_target", path,
            f"Box plot of '{top_feature}' split by {target_col}",
        )
        logger.info("Saved top-feature vs. target chart → %s", path)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def run(
        self,
        eda_report_path: str,
        ml_report_path: str,
        cleaned_data_path: str,
        target_col: str = "is_late_delivery",
        output_dir: str = "workspace/visualizations",
    ) -> tuple[bool, str]:
        """Generate all charts from the EDA report, ML report, and cleaned data.

        Parameters
        ----------
        eda_report_path : str
            Path to the EDA agent's JSON report.
        ml_report_path : str
            Path to the ML agent's JSON report.
        cleaned_data_path : str
            Path to the cleaned (pre-feature-engineering) CSV, used for
            distribution histograms and the box plot.
        target_col : str
            Name of the prediction target column in cleaned_data_path.
        output_dir : str
            Directory where PNG files and the visualization report are written.

        Returns
        -------
        (success, report_path_or_error_message)
        """
        logger.info(
            "Starting visualization run  eda=%s  ml=%s  data=%s  out=%s",
            eda_report_path, ml_report_path, cleaned_data_path, output_dir,
        )

        os.makedirs(output_dir, exist_ok=True)
        report = VisualizationReport()

        # --- Load EDA report ---
        eda = {}
        try:
            with open(eda_report_path) as f:
                eda = json.load(f)
        except Exception as exc:
            logger.warning("Could not load EDA report: %s", exc)

        # --- Load ML report ---
        ml = {}
        try:
            with open(ml_report_path) as f:
                ml = json.load(f)
        except Exception as exc:
            logger.warning("Could not load ML report: %s", exc)

        # --- Load cleaned data ---
        df = pd.DataFrame()
        try:
            df = pd.read_csv(cleaned_data_path)
            logger.info("Loaded data: %s", df.shape)
        except Exception as exc:
            logger.warning("Could not load cleaned data: %s", exc)

        feature_importances: dict = ml.get("feature_importances") or {}
        corr_matrix: dict = eda.get("correlation_matrix") or {}
        confusion_matrix = ml.get("confusion_matrix")
        threshold_metrics = ml.get("threshold_metrics")
        task_type: str = ml.get("task_type", "binary_classification")

        # --- Generate charts ---
        self._chart_distributions(df, feature_importances, output_dir, report)
        self._chart_correlation_heatmap(corr_matrix, output_dir, report)
        self._chart_feature_importance(feature_importances, output_dir, report)
        self._chart_confusion_matrix(confusion_matrix, output_dir, report, task_type)
        self._chart_threshold_tradeoff(threshold_metrics, output_dir, report)
        self._chart_top_feature_vs_target(
            df, target_col, feature_importances, output_dir, report
        )

        self.report_ = report

        report_path = os.path.join(output_dir, "visualization_report.json")
        with open(report_path, "w") as f:
            json.dump(report.to_dict(), f, indent=2)
        logger.info(
            "Visualization complete: %d charts generated, %d skipped",
            len(report.charts), len(report.skipped),
        )
        logger.info("Visualization report written to %s", report_path)

        return True, report_path


if __name__ == "__main__":
    import sys

    agent = VisualizationAgent()
    success, result = agent.run(
        eda_report_path="data/processed/olist_flattened_cleaned_eda_report.json",
        ml_report_path="data/processed/olist_flattened_cleaned_features_ml_report.json",
        cleaned_data_path="data/processed/olist_flattened_cleaned.csv",
        output_dir="workspace/visualizations",
    )
    if success:
        print(f"Success. Report at: {result}")
        for chart in agent.report_.charts:
            size_kb = os.path.getsize(chart["path"]) // 1024
            print(f"  {chart['name']:35s}  {size_kb:>5} KB  {chart['path']}")
    else:
        print(f"Failed: {result}")
        sys.exit(1)
